# 2-5. PyTorch 기초 - Tensor
## Tensor란?
Tensor란 데이터를 표현하는 단위로, 다차원 배열의 일반화된 모습이다. 
PyTorch에서 Tensor를 가지고 연산을 수행하면, 해당 연산은 Computational Graph 상에 표현되고, 나중에 Backward propagation을 통해 Gradient를 계산할 수 있다.

## Initializing a tensor
Tensor를 정의하는 방법은 다음과 같다. 
1. 지정된 값으로 초기화
2. 랜덤한 값으로 초기화
3. Numpy array로부터 초기화

In [1]:
# Import related library
import numpy as np 
import torch

## 초기화 방법 1: 지정된 값으로 Tensor 초기화

In [2]:
data = [[1,2], [3,4]]
x_data = torch.tensor(data)

In [3]:
x_data

tensor([[1, 2],
        [3, 4]])

In [4]:
x_data.dtype

torch.int64

## 초기화 방법 2: 랜덤한 값으로 Tensor 초기화

In [7]:
shape = (2,3)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f'Random Tensor: \n {rand_tensor} \n')
print(f'Ones Tensor: \n {ones_tensor} \n')
print(f'Zeros Tensor: \n {zeros_tensor} \n')

Random Tensor: 
 tensor([[0.5374, 0.2631, 0.1488],
        [0.6885, 0.8902, 0.7685]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]]) 



## 초기화 방법 3: Numpy 배열로부터 초기화

In [8]:
data = [[1,2],[3,4]]
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

In [9]:
x_np

tensor([[1, 2],
        [3, 4]])

In [10]:
x_np.dtype

torch.int64

## Tensor 데이터의 형식 지정
Tensor의 데이터 형식
1. 정수 int
    1-1. `torch.int8`, `torch.int16`, `torch.int32`, `torch.int64` (`torch.long`)
    1-2. `torch.uint8`: unsigend integer로 양의 정수 0 ~ 255 숫자만 포함, 주로 이미지 데이터 다룰 때 사용
2. float
    2-1. `torch.float16`, `torch.float32`, `torch.float64`
3. boolean
4. etc.

### torch.float32 형식으로 초기화

In [11]:
data = [[1,2],[3,4]]
x_data = torch.tensor(data, dtype=torch.float32)

In [12]:
x_data

tensor([[1., 2.],
        [3., 4.]])

In [13]:
x_data.dtype

torch.float32

### torch.uint8 형식으로 초기화

In [14]:
data = [[1,2], [3,4]]
x_data = torch.tensor(data, dtype=torch.uint8)

In [15]:
x_data

tensor([[1, 2],
        [3, 4]], dtype=torch.uint8)

In [16]:
x_data.dtype

torch.uint8

### 다른 dtype으로 변환

In [17]:
x_data = x_data.to(torch.float16)
x_data.dtype

torch.float16

## 다른 Device로 Tensor 옮기기
1. GPU가 사용가능한지 확인하기
2. 다른 Device로 Tensor 옮기기
3. 어떤 Device 상에 Tensor가 있는지 확인하기

### GPU가 사용가능한지 확인하기

In [18]:
torch.cuda.is_available()

False

In [19]:
torch.backends.mps.is_available()

True

### GPU로 Tensor 옮기기

In [23]:
x_data = x_data.to('mps')

### CPU로 Tensor 옮기기

In [25]:
# 둘은 동일한 효과
x_data = x_data.cpu()
x_data = x_data.to('cpu')

### 어떤 Device 상에 Tensor가 있는지 확인하기

In [26]:
x_data.device

device(type='cpu')

## Tensor를 활용한 연산
1. Indexing and slicing
2. Concatenation
3. Arithmetic
4. Inplace-operation

### Indexing

In [27]:
tensor = torch.ones(4,4)

In [28]:
print(f'First row: {tensor[0]}')
print(f'First column: {tensor[:,0]}')
print(f'Last column: {tensor[:,-1]}')
tensor[:,1] = 0
print(tensor)

First row: tensor([1., 1., 1., 1.])
First column: tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


### Concatenation

In [31]:
t1 = torch.cat([tensor, tensor, tensor], dim=0)
t1

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [32]:
t1.shape

torch.Size([12, 4])

### Arithmetic

In [33]:
# matrix multiplication
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

In [34]:
y1

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])

In [35]:
y2

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])

In [36]:
# element-wise operation
z1 = tensor * tensor
z2 = tensor.mul(tensor)

In [37]:
z1

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [38]:
z2

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

### Inplace operation

In [39]:
print(f'{tensor}')

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [40]:
tensor.add_(5) # add and override

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])

In [41]:
tensor

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])

In [42]:
tensor.add(5)

tensor([[11., 10., 11., 11.],
        [11., 10., 11., 11.],
        [11., 10., 11., 11.],
        [11., 10., 11., 11.]])

In [43]:
tensor

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])